---
chdir: "/www/jantafora.com"
environment: development
address: 0.0.0.0
port: 5000
timeout: 30
log: "/www/jantafora.com/log/thin.log"
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
servers: 3
daemonize: true
